<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<Import Project="../../Nu/Nu.targets" />

	<ItemGroup>
		<None Include="Assets\*" />
		<None Include="Assets\*\*" />
		<Compile Include="Assets.fs" />
		<Compile Include="Constants.fs" />
		<Compile Include="Simulants.fs" />
		<Compile Include="Data.fs" />
		<Compile Include="Algorithm.fs" />
		<Compile Include="Events.fs" />
		<Compile Include="WayPoint.fs" />
		<Compile Include="SpawnPoint.fs" />
		<Compile Include="InsertionSpot.fs" />
		<Compile Include="DoorSpot.fs" />
		<Compile Include="InvestigationSpot.fs" />
		<Compile Include="HidingSpot.fs" />
		<Compile Include="Character.fs" />
		<Compile Include="Hunter.fs" />
		<Compile Include="Stalker.fs" />
		<Compile Include="Player.fs" />
		<Compile Include="Gameplay.fs" />
		<Compile Include="MyGame.fs" />
		<Compile Include="MyGamePlugin.fs" />
		<Compile Include="Program.fs" />
		<Content Include="AssetGraph.nuag">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Overlayer.nuol">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<None Include="App.config" />
	</ItemGroup>

</Project>